import mongoose from "mongoose";
const questionSchema = new mongoose.Schema(                     // Question Schema
  {
    question:                                                   // The interview question generated by the AI
    {
      type: String,
      required: true,
    },
    answer:                                                         // The answer given by the candidate 
    {
      type: String,
      default: "",
    },
    score:                                                          // Score given by AI after evaluating the candidate's answer
    {
      type: Number,
      default: null,
    },
    feedback:                                                // Question-specific AI feedback 
    {
      type: String,
      default: "",
    },
  },
  {
    _id: false,                         // Mongo DB will create separate _id for each embedded question object
  }
);

const interviewSchema = new mongoose.Schema(                          // Main Interview Schema
  {
    candidate:                                                    // This creates a reference to the User collection 
    {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    interviewType:                                        // Defines the broad type of interview(Eg: Technical, HR)
    {
      type: String,
      required: true,
    },
    subject:                                              // Defines the interview subject or domain(Eg: AIML)
    {
      type: String,
      required: true,
    },
    topic:                                                // Defines the specific topic within the subject(Eg: Node.js, hashing)
    {
      type: String,
      required: true,
    },
    targetRole:                                       // The job role the candidate is preparing for(Eg: ML Engineer)
    {
      type: String,
      required: true,
    },
    difficulty:                                   // Difficulty selected for the interview
    {
      type: String,
      enum: ["Easy", "Medium", "Hard"],             // enum prevents unsupported difficulty values
      required: true,
    },
    numberOfQuestions:                                   // Total number of questions planned for this interview
    {
      type: Number,
      required: true,
    },
    questions:                                      // Stores all questions belonging to this interview session
    {                                
      type: [questionSchema],
      default: [],
    },
    status:                                                // Tracks the current lifecycle state of the interview
    {
      type: String,
      enum: ["Not Started", "In Progress", "Completed"],
      default: "Not Started",
    },
    overallScore:                                                     // Final overall interview score
    {
      type: Number,
      default: null,
    },
    finalFeedback:                                              // Final AI-generated feedback for the complete interview 
    {
      type: String,
      default: "",
    },
    },
    {
      timestamps: true,
    }
);

const Interview = mongoose.model("Interview", interviewSchema);       // Creates the Interview model

export default Interview;